### ISSUE TITLE
Input fields too short

### ISSUE THREAD

**Issue by furynick** [jbostoen/itop-jb-lnkconnectablecitoconnectableci#2]
After installing extension on a fresh iTop 2.7.5 there's a size problem on input fields
![image](https://user-images.githubusercontent.com/3520080/127770586-61647fe4-7781-453f-88f5-c10dcc18e145.png)

**Comment by jbostoen** [comment]
Thanks for confirming you also have it with native iTop linked classes :)
So it's simply an issue of not enough room to properly show all the fields?

You could either show less fields, or temporarily collapse the left menu, decrease zoom level of your browser, ...

Anyhow, it's an iTop thing, I won't consider this as a bug.
